---
downloads: /etc/ansible/downloads/

# Configure Homebrew
homebrew_installed_packages:
  - git
  - go
  - hub
  - node
  - openssl
  - pv
  - ssh-copy-id
  - wget
  # Install GNU core utilities (those that come with OS X are outdated).
  # Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
  - coreutils

#homebrew_taps:
#  - homebrew/core
#  - caskroom/cask

#homebrew_cask_appdir: /Applications
#homebrew_cask_apps:
#  - docker
#  - google-chrome
#  - slack
#  - sublime-text
#  - vagrant
#  - virtualbox

# Configure pip
# (https://galaxy.ansible.com/bobbyrenwick/pip/)

##  Specifies where get-pip.py should be downloaded to
#pip_download_dest: /tmp

##  Defaults to None, to install the latest version (If pip is installed, upgrades to the latest pip version available)
##  Can be set to a specific version, e.g. "6.0.8" to force installation of that version.
##  Can be set explicitly to "LATEST" or "latest" to force upgrade to the latest available version (same behaviour as None).
#pip_version: None

##  Specifies what Python executable to use
#python: python

##  Specifies what pip executable to check and use
#pip: pip

## Specifies a HTTP proxy, if you have to use it (e.g. behind firewall)
#pip_proxy: ``
