---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - default.config.yml

#  pre_tasks:
#    - include_vars: "{{ item }}"
#      with_fileglob:
#        - ../config.yml
#      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

  tasks:
    - import_tasks: tasks/ansible-setup.yml
