---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - ../configs/homebrew.yml
    - ../configs/dotfiles.yml
#    - ../configs/default.config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
#    - role: bobbyrenwick.pip
