---
- hosts: all
  connection: local
  become: true
#  become_user: root
#  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - ../configs/osx-defaults.yml

  roles:
    - role: lafarer.osx-defaults

#  tasks:
#    - name: "AppStore - Automatically check for updates"
#      osx_defaults:
#        domain: '/Library/Preferences/com.apple.SoftwareUpdate'
#        key: 'AutomaticCheckEnabled'
#        type: bool
#        value: True
##      when: AppStore_AutomaticCheckEnabled is defined
##      notify: restart AppStore
