---
# Assumes python is installed on OSX
- name: "Install pip"
  command: "easy_install pip"

- name: Install all pip packages
  shell: "pip install {{ item }}"
  failed_when: false
  check_mode: no
  changed_when: false
  with_items: "{{ pip_packages }}"
