---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - configs/homebrew.yml
    - configs/mas.yml
    - configs/dotfiles.yml
    - configs/git-config.yml
    - configs/pip.yml

  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas
    - role: geerlingguy.dotfiles
    - role: bobbyrenwick.pip
