---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - configs/homebrew.yml
    # TODO: Re-enable with issue is fixed: https://github.com/mas-cli/mas/issues/107
#    - configs/mas.yml
    - configs/dotfiles.yml
    - configs/dock.yml

  roles:
    - role: geerlingguy.homebrew
    # TODO: Re-enable with issue is fixed: https://github.com/mas-cli/mas/issues/107
#    - role: geerlingguy.mas
    - role: geerlingguy.dotfiles

  tasks:
    - include_tasks: tasks/pip.yml
    - include_tasks: tasks/dock.yml
    - include_tasks: tasks/fish-shell.yml
