---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - configs/homebrew.yml
    - configs/mas.yml
    - configs/dotfiles.yml
    - configs/pip.yml
    - configs/dock.yml
    - configs/osx-defaults.yml

  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas
    - role: geerlingguy.dotfiles
    - role: bobbyrenwick.pip
    - role: lafarer.osx-defaults

  tasks:
    - include_tasks: tasks/dock.yml
